# .github/models/gpt5-review.yml
model: azure-openai/gpt-5-chat
name: PR Auto Review (GPT-5)
description: >
  Αυτόματο code review για PRs, χρησιμοποιώντας GPT-5 Chat.
  Δίνει feedback και προτάσεις βελτίωσης στον κώδικα.

on:
  pull_request:
    types: [opened, synchronize, reopened]

inputs:
  - name: diff
    type: diff
    description: "Ο diff του PR για ανάλυση"

completion:
  max_output_tokens: 800
  temperature: 0.2

instructions: |
  Εξήγησε τις αλλαγές συνοπτικά και εντόπισε πιθανά προβλήματα:
  - syntax errors
  - imports / circular dependencies
  - stability risks (cron jobs, Telegram handlers, RPC)
  - συμβατότητα με το canonical main.py του project
  Αν όλα είναι ΟΚ, γράψε: "✅ Review passed — safe to merge."
