name: ✅ CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install flake8 pytest

      - name: Lint check
        run: flake8 . --exclude=.venv --max-line-length=120

      - name: Run tests
        run: pytest -q || echo "⚠️ Tests failed (non-blocking)"
