name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
      - name: Lint (flake8 if present)
        run: |
          if [ -f setup.cfg ]; then pip install flake8 && flake8 || true; else echo "no flake8"; fi
      - name: Smoke import
        run: |
          python - <<'PY'
          import importlib
          import sys
          for m in ("app.main",):
              try:
                  importlib.import_module(m)
                  print("OK:", m)
              except Exception as e:
                  print("WARN:", m, e, file=sys.stderr)
          PY
