name: ✅ CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install flake8 pytest

      - name: Lint check
        run: flake8 . --exclude=.venv --max-line-length=120

      - name: Run tests (fail only on failing suite)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo 'No tests/ directory; skipping.'
          fi
