name: 🔄 ChatGPT Full Sync (PR-based)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate MANIFEST.md
        run: |
          python - <<'EOF'
          import os, pathlib
          files = []
          for root, dirs, filenames in os.walk('.', topdown=True):
              if '.git' in root or '.venv' in root or 'venv' in root:
                  continue
              for f in filenames:
                  files.append(os.path.join(root, f))
          files = sorted(pathlib.Path(p).as_posix() for p in files)
          with open('MANIFEST.md', 'w', encoding='utf-8') as fp:
              fp.write('# 🧾 Repo Manifest\n\n')
              for p in files:
                  fp.write(f'- {p}\n')
          EOF

      - name: Create PR for MANIFEST update
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "🤖 Sync: Auto-update MANIFEST.md"
          title: "🤖 Sync: Auto-update MANIFEST.md"
          body: "Automated repo manifest refresh to keep ChatGPT in sync."
          branch: "chatgpt/sync-manifest"
          delete-branch: true

      - name: Enable auto-merge (squash)
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
