name: ChatGPT Full Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Generate MANIFEST.md
        run: |
          echo '# MANIFEST (auto)' > MANIFEST.md
          echo '' >> MANIFEST.md
          find . -type f ! -path './.git/*' | sort >> MANIFEST.md

      - name: Commit & push MANIFEST.md
        env:
          GH_FINE_TOKEN: ${{ secrets.GH_FINE_TOKEN }}
        run: |
          git config user.name 'chatgpt-codex-bot'
          git config user.email 'bot@openai'
          git add MANIFEST.md
          git commit -m 'auto-update MANIFEST.md' || echo 'No changes'
          git push origin HEAD:${GITHUB_REF#refs/heads/} || true
