name: 🔄 ChatGPT Full Sync (PR-based)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Rebuild MANIFEST.md
        run: |
          python - <<'EOF'
          import os
          files = []
          for root, dirs, filenames in os.walk(".", topdown=True):
              if ".git" in root.split(os.sep):
                  continue
              for f in filenames:
                  files.append(os.path.join(root, f))
          files = sorted(files)
          with open("MANIFEST.md", "w", encoding="utf-8") as fp:
              fp.write("# 🧾 Repo Manifest\n\n")
              fp.write("\n".join(files))
          EOF

      - name: Commit changes (if any)
        run: |
          git config user.name "ChatGPT Sync Agent"
          git config user.email "agent@openai.com"
          git add MANIFEST.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "🤖 Auto-update MANIFEST.md"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "🤖 Auto-update MANIFEST.md"
          branch: chore/sync-manifest-${{ github.run_id }}
          title: "🤖 Sync: Auto-update MANIFEST.md"
          body: |
            This PR was generated by the Sync workflow.
            - Updates `MANIFEST.md`
            - Uses PR flow to comply with protected `main`.
          labels: |
            sync
            automated
          delete-branch: true
